CREATE TABLE IF NOT EXISTS sky_tower_settings (
  id TINYINT UNSIGNED NOT NULL PRIMARY KEY,
  raw_text MEDIUMTEXT NOT NULL,
  updated_by BIGINT UNSIGNED NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_sky_tower_settings_updated_by
    FOREIGN KEY (updated_by) REFERENCES admin_users(id)
    ON DELETE SET NULL
);
