import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";
import pagesConfig from "../pages.json";

const miniappRoot = resolve(import.meta.dirname, "..");

function readMiniappFile(path: string): string {
  return readFileSync(resolve(miniappRoot, path), "utf8");
}

describe("miniapp guides navigation", () => {
  it("registers guides pages and exposes the guides tab between resources and profile", () => {
    const paths = pagesConfig.pages.map((page) => page.path);
    const tabBar = readMiniappFile("custom-tab-bar/index.js");
    const guidesPage = readMiniappFile("pages/guides/index.vue");
    const profilePage = readMiniappFile("pages/profile/index.vue");
    const rootApp = readMiniappFile("app.json");

    expect(paths).toContain("pages/guides/index");
    expect(paths).toContain("pages/guides/redeem-codes");
    expect(paths).toContain("pages/guides/dragon-ball-system");
    expect(paths).toContain("pages/guides/deep-sea-battle");
    expect(paths).toContain("pages/guides/deep-sea-boss");
    expect(paths).toContain("pages/guides/maelstrom");
    expect(paths).toContain("pages/guides/maelstrom-boss");
    expect(paths).toContain("pages/guides/sky-tower");
    expect(paths).toContain("pages/guides/dungeon-materials");
    expect(paths).toContain("pages/guides/dungeon-guide");
    expect(paths).toContain("pages/guides/card-upgrade");
    expect(paths).toContain("pages/guides/season-challenge");
    expect(paths).toContain("pages/guides/health-calculator");
    expect(paths).toContain("pages/guides/additional-calculator");
    expect(rootApp).toContain("devtools/mp-weixin/pages/guides/dungeon-materials");
    expect(rootApp).toContain("devtools/mp-weixin/pages/guides/dungeon-guide");
    expect(rootApp).toContain("devtools/mp-weixin/pages/guides/card-upgrade");
    expect(rootApp).toContain("devtools/mp-weixin/pages/guides/season-challenge");
    expect(rootApp).toContain("devtools/mp-weixin/pages/guides/additional-calculator");
    expect(paths).not.toContain("pages/guides/check-in-webview");
    expect(pagesConfig.tabBar.list.map((item) => item.text)).toEqual(["资源", "攻略", "我的"]);
    expect(tabBar).toContain('{ pagePath: "pages/guides/index", text: "攻略" }');
    expect(guidesPage).toContain("syncCustomTabBarSelected(1)");
    expect(profilePage).toContain("syncCustomTabBarSelected(2)");
  });

  it("loads redeem codes from the API and copies the tapped code", () => {
    const apiClient = readMiniappFile("api/client.ts");
    const guidesPage = readMiniappFile("pages/guides/index.vue");
    const redeemCodePage = readMiniappFile("pages/guides/redeem-codes.vue");

    expect(apiClient).toContain("listRedeemCodes");
    expect(apiClient).toContain("/api/redeem-codes");
    expect(apiClient).toContain("getAppConfig");
    expect(apiClient).toContain("/api/app-config");
    expect(apiClient).toContain("dungeonMaterialImageUrl");
    expect(apiClient).toContain("dungeonGuideImageUrl");
    expect(apiClient).toContain("dungeonGuideImageUrls");
    expect(guidesPage).toContain("@tap=\"openRedeemCodes\"");
    expect(guidesPage).toContain("兑换码");
    expect(guidesPage).toContain("@tap=\"openCheckIn\"");
    expect(guidesPage).toContain("签到");
    expect(guidesPage).toContain("getAppConfig");
    expect(guidesPage).toContain("dungeonMaterialImageUrl");
    expect(guidesPage).toContain("dungeonGuideImageUrl");
    expect(guidesPage).toContain("hasActivityEntries");
    expect(guidesPage).toContain("暂未配置签到入口");
    expect(guidesPage).toContain("uni.setClipboardData");
    expect(guidesPage).toContain("签到链接已复制");
    expect(guidesPage).toContain("请在微信内打开");
    expect(guidesPage).not.toContain("check-in-webview");
    expect(guidesPage).toContain("uni.showShareMenu");
    expect(guidesPage).toContain("onShareAppMessage");
    expect(guidesPage).toContain("onShareTimeline");
    expect(guidesPage).toContain("buildGuidesShare");
    expect(redeemCodePage).toContain("listRedeemCodes");
    expect(redeemCodePage).toContain("uni.setClipboardData");
    expect(redeemCodePage).toContain("uni.showShareMenu");
    expect(redeemCodePage).toContain("onShareAppMessage");
    expect(redeemCodePage).toContain("onShareTimeline");
    expect(redeemCodePage).toContain("buildRedeemCodesShare");
    expect(redeemCodePage).toContain("暂无兑换码");
    expect(redeemCodePage).toContain("点击复制兑换码");
    expect(redeemCodePage).toContain("#071112");
    expect(redeemCodePage).toContain("repeating-linear-gradient");
    expect(redeemCodePage).toContain("rgba(246, 196, 83, 0.34)");
    expect(redeemCodePage).toContain("tap-hint");
    expect(redeemCodePage).not.toContain("background: #f8fafc");
    expect(redeemCodePage).not.toContain("background: #fff;");
  });

  it("adds a fixed dragon ball system guide entry and content page", () => {
    const guidesPage = readMiniappFile("pages/guides/index.vue");
    const dragonBallPage = readMiniappFile("pages/guides/dragon-ball-system.vue");
    const deepSeaBattlePage = readMiniappFile("pages/guides/deep-sea-battle.vue");
    const deepSeaBossPage = readMiniappFile("pages/guides/deep-sea-boss.vue");
    const maelstromPage = readMiniappFile("pages/guides/maelstrom.vue");
    const maelstromBossPage = readMiniappFile("pages/guides/maelstrom-boss.vue");
    const skyTowerPage = readMiniappFile("pages/guides/sky-tower.vue");
    const dungeonMaterialsPage = readMiniappFile("pages/guides/dungeon-materials.vue");
    const dungeonGuidePage = readMiniappFile("pages/guides/dungeon-guide.vue");
    const cardUpgradePage = readMiniappFile("pages/guides/card-upgrade.vue");
    const seasonChallengePage = readMiniappFile("pages/guides/season-challenge.vue");
    const healthCalculatorPage = readMiniappFile("pages/guides/health-calculator.vue");
    const additionalCalculatorPage = readMiniappFile("pages/guides/additional-calculator.vue");
    const apiClient = readMiniappFile("api/client.ts");

    expect(guidesPage).toContain("@tap=\"openDeepSeaBattle\"");
    expect(guidesPage).toContain("/pages/guides/deep-sea-battle");
    expect(guidesPage).toContain("@tap=\"openMaelstrom\"");
    expect(guidesPage).toContain("/pages/guides/maelstrom");
    expect(guidesPage).toContain("大漩涡");
    expect(guidesPage).toContain("@tap=\"openSkyTower\"");
    expect(guidesPage).toContain("/pages/guides/sky-tower");
    expect(guidesPage).toContain("天空塔");
    expect(guidesPage).toContain("活动入口");
    expect(guidesPage).toContain("v-if=\"hasActivityEntries\"");
    expect(guidesPage).toContain("v-if=\"dungeonMaterialImageUrl\"");
    expect(guidesPage).toContain("v-if=\"hasDungeonGuideImages\"");
    expect(guidesPage).toContain("@tap=\"openDungeonMaterials\"");
    expect(guidesPage).toContain("/pages/guides/dungeon-materials");
    expect(guidesPage).toContain("活动材料");
    expect(guidesPage).toContain("材料图片查看");
    expect(guidesPage).toContain("@tap=\"openDungeonGuide\"");
    expect(guidesPage).toContain("/pages/guides/dungeon-guide");
    expect(guidesPage).toContain("活动攻略");
    expect(guidesPage).toContain("攻略图片查看");
    expect(guidesPage.indexOf("活动入口")).toBeLessThan(guidesPage.indexOf("活动材料"));
    expect(guidesPage.indexOf("活动材料")).toBeLessThan(guidesPage.indexOf("活动攻略"));
    expect(guidesPage.indexOf("活动攻略")).toBeLessThan(guidesPage.indexOf("副本计算"));
    expect(guidesPage).toContain("基础功能");
    expect(guidesPage).toContain("@tap=\"openCardUpgrade\"");
    expect(guidesPage).toContain("/pages/guides/card-upgrade");
    expect(guidesPage).toContain("卡牌升级");
    expect(guidesPage).toContain("英雄卡牌升级材料计算");
    expect(guidesPage).toContain("@tap=\"openSeasonChallenge\"");
    expect(guidesPage).toContain("/pages/guides/season-challenge");
    expect(guidesPage).toContain("赛季挑战");
    expect(guidesPage).toContain("赛季积分与奖章计算");
    expect(guidesPage.indexOf("基础功能")).toBeLessThan(guidesPage.indexOf("卡牌升级"));
    expect(guidesPage.indexOf("卡牌升级")).toBeLessThan(guidesPage.indexOf("赛季挑战"));
    expect(guidesPage.indexOf("赛季挑战")).toBeLessThan(guidesPage.indexOf("副本计算"));
    expect(guidesPage.indexOf("副本计算")).toBeLessThan(guidesPage.indexOf("深海之战"));
    expect(guidesPage.indexOf("深海之战")).toBeLessThan(guidesPage.indexOf("大漩涡"));
    expect(guidesPage.indexOf("大漩涡")).toBeLessThan(guidesPage.indexOf("天空塔"));
    expect(guidesPage.indexOf("天空塔")).toBeLessThan(guidesPage.indexOf("其它"));
    expect(guidesPage.indexOf("深海之战")).toBeLessThan(guidesPage.indexOf("其它"));
    expect(guidesPage.indexOf("其它")).toBeLessThan(guidesPage.indexOf("血量计算"));
    expect(guidesPage.indexOf("血量计算")).toBeLessThan(guidesPage.indexOf("附加计算"));
    expect(guidesPage.indexOf("附加计算")).toBeLessThan(guidesPage.indexOf("签到"));
    expect(guidesPage.indexOf("其它")).toBeLessThan(guidesPage.indexOf("龙珠体系"));
    expect(guidesPage).toContain("@tap=\"openHealthCalculator\"");
    expect(guidesPage).toContain("/pages/guides/health-calculator");
    expect(guidesPage).toContain("战车生命加成计算");
    expect(guidesPage).toContain("@tap=\"openAdditionalCalculator\"");
    expect(guidesPage).toContain("/pages/guides/additional-calculator");
    expect(guidesPage).toContain("附加伤害加成计算");
    expect(guidesPage).toContain("@tap=\"openDragonBallSystem\"");
    expect(guidesPage).toContain("/pages/guides/dragon-ball-system");
    expect(guidesPage).toContain("龙珠体系");
    expect(dragonBallPage).toContain("品质属性范围");
    expect(dragonBallPage).toContain("查看龙珠系统介绍");
    expect(dragonBallPage).toContain("龙珠获取方式");
    expect(dragonBallPage).toContain("波澜之主成就");
    expect(dragonBallPage).toContain("第1名礼盒概率");
    expect(dragonBallPage).toContain("501-1000名礼盒概率");
    expect(dragonBallPage).toContain("onShareAppMessage");
    expect(dragonBallPage).toContain("buildDragonBallSystemShare");
    expect(dragonBallPage).toContain("#071112");
    expect(deepSeaBattlePage).toContain("deepSeaMapRows");
    expect(deepSeaBattlePage).toContain("openDeepSeaBoss");
    expect(deepSeaBattlePage).toContain("buildDeepSeaBattleShare");
    expect(deepSeaBattlePage).toContain("royal-city");
    expect(deepSeaBattlePage).toContain("#071112");
    expect(deepSeaBossPage).toContain("calculateDeepSeaBoss");
    expect(deepSeaBossPage).toContain("levelOptions");
    expect(deepSeaBossPage).toContain("装备");
    expect(deepSeaBossPage).toContain("魔抗减免");
    expect(deepSeaBossPage).toContain("伤害减免");
    expect(deepSeaBossPage).toContain("buildDeepSeaBossShare");
    expect(maelstromPage).toContain("maelstromSections");
    expect(maelstromPage).toContain("openMaelstromBoss");
    expect(maelstromPage).toContain("buildMaelstromShare");
    expect(maelstromPage).toContain("龙族·红龙");
    expect(maelstromPage).toContain("#071112");
    expect(maelstromBossPage).toContain("calculateMaelstromBoss");
    expect(maelstromBossPage).toContain("Boss 属性");
    expect(maelstromBossPage).toContain("伤害演算");
    expect(maelstromBossPage).toContain("战车血量");
    expect(maelstromBossPage).toContain("魔抗减免");
    expect(maelstromBossPage).toContain("纯粹减免");
    expect(maelstromBossPage).toContain("真伤减免");
    expect(maelstromBossPage).toContain("buildMaelstromBossShare");
    expect(skyTowerPage).toContain("skyTowerFloorPages");
    expect(skyTowerPage).toContain("selectFloor");
    expect(skyTowerPage).toContain("奖励信息");
    expect(skyTowerPage).toContain("阵容说明");
    expect(skyTowerPage).toContain("lineup-board");
    expect(skyTowerPage).toContain("左车");
    expect(skyTowerPage).toContain("右车");
    expect(skyTowerPage).toContain("leftHeroSlots");
    expect(skyTowerPage).toContain("rightHeroSlots");
    expect(skyTowerPage).toContain("战术备注");
    expect(skyTowerPage).toContain("资料待补充");
    expect(skyTowerPage).toContain("buildSkyTowerShare");
    expect(skyTowerPage).toContain("onShareAppMessage");
    expect(skyTowerPage).toContain("getSkyTowerConfig");
    expect(skyTowerPage).toContain("loadSkyTowerConfig");
    expect(skyTowerPage).toContain("加载失败");
    expect(skyTowerPage).toContain("#071112");
    expect(dungeonMaterialsPage).toContain("dungeonMaterialImageUrl");
    expect(dungeonMaterialsPage).toContain("活动材料");
    expect(dungeonMaterialsPage).toContain("暂未配置活动材料图片");
    expect(dungeonMaterialsPage).toContain("图片加载失败");
    expect(dungeonMaterialsPage).toContain("uni.previewImage");
    expect(dungeonMaterialsPage).toContain("buildDungeonMaterialsShare");
    expect(dungeonMaterialsPage).toContain("onShareAppMessage");
    expect(dungeonMaterialsPage).toContain("onShareTimeline");
    expect(dungeonMaterialsPage).toContain("#071112");
    expect(dungeonGuidePage).toContain("dungeonGuideImageUrls");
    expect(dungeonGuidePage).toContain("活动攻略");
    expect(dungeonGuidePage).toContain("暂未配置活动攻略图片");
    expect(dungeonGuidePage).toContain("v-for=\"(imageUrl, index) in dungeonGuideImageUrls\"");
    expect(dungeonGuidePage).toContain("攻略图 {{ index + 1 }}");
    expect(dungeonGuidePage).toContain("图片加载失败");
    expect(dungeonGuidePage).toContain("uni.previewImage");
    expect(dungeonGuidePage).toContain("urls: dungeonGuideImageUrls.value");
    expect(dungeonGuidePage).toContain("buildDungeonGuideShare");
    expect(dungeonGuidePage).toContain("onShareAppMessage");
    expect(dungeonGuidePage).toContain("onShareTimeline");
    expect(dungeonGuidePage).toContain("#071112");
    expect(cardUpgradePage).toContain("calculateCardUpgrade");
    expect(cardUpgradePage).toContain("卡牌类型");
    expect(cardUpgradePage).toContain("当前等级");
    expect(cardUpgradePage).toContain("目标等级");
    expect(cardUpgradePage).toContain("已有卡牌数");
    expect(cardUpgradePage).toContain("还需卡牌");
    expect(cardUpgradePage).toContain("恶魔果");
    expect(cardUpgradePage).toContain("buildCardUpgradeShare");
    expect(cardUpgradePage).toContain("onShareAppMessage");
    expect(cardUpgradePage).toContain("onShareTimeline");
    expect(cardUpgradePage).toContain("#071112");
    expect(seasonChallengePage).toContain("calculateSeasonChallenge");
    expect(seasonChallengePage).toContain("toggleSeasonChallengeStep");
    expect(seasonChallengePage).toContain("guideSeasonChallengeProgress");
    expect(seasonChallengePage).toContain("guideSeasonChallengeOpenSection");
    expect(seasonChallengePage).toContain("总积分");
    expect(seasonChallengePage).toContain("奖章");
    expect(seasonChallengePage).toContain("连胜");
    expect(seasonChallengePage).toContain("熟练度");
    expect(seasonChallengePage).toContain("寒冰堡");
    expect(seasonChallengePage).toContain("英雄等级");
    expect(seasonChallengePage).toContain("大航海");
    expect(seasonChallengePage).toContain("合作");
    expect(seasonChallengePage).toContain("最高杯");
    expect(seasonChallengePage).toContain("登录天数");
    expect(seasonChallengePage).toContain("充值");
    expect(seasonChallengePage).toContain("buildSeasonChallengeShare");
    expect(seasonChallengePage).toContain("onShareAppMessage");
    expect(seasonChallengePage).toContain("onShareTimeline");
    expect(seasonChallengePage).toContain("#071112");
    expect(healthCalculatorPage).toContain("calculateHealth");
    expect(healthCalculatorPage).toContain("主卡血量");
    expect(healthCalculatorPage).toContain("副卡血量");
    expect(healthCalculatorPage).toContain("装备");
    expect(healthCalculatorPage).toContain("幻皮");
    expect(healthCalculatorPage).toContain("满星死神");
    expect(healthCalculatorPage).toContain("绿星死神");
    expect(healthCalculatorPage).toContain("死神皮肤");
    expect(healthCalculatorPage).toContain("魔化死神");
    expect(healthCalculatorPage).toContain("牧师个数");
    expect(healthCalculatorPage).toContain("魔化酋长");
    expect(healthCalculatorPage).toContain("魔化土灵");
    expect(healthCalculatorPage).toContain("咕咕皮");
    expect(healthCalculatorPage).toContain("宋江羁绊数");
    expect(healthCalculatorPage).toContain("占星血量");
    expect(healthCalculatorPage).toContain("血车");
    expect(healthCalculatorPage).toContain("buildHealthCalculatorShare");
    expect(healthCalculatorPage).toContain("onShareAppMessage");
    expect(healthCalculatorPage).toContain("#071112");
    expect(additionalCalculatorPage).toContain("calculateAdditionalDamage");
    expect(additionalCalculatorPage).toContain("固定附加");
    expect(additionalCalculatorPage).toContain("水灵等级");
    expect(additionalCalculatorPage).toContain("水灵皮肤");
    expect(additionalCalculatorPage).toContain("魔化水灵");
    expect(additionalCalculatorPage).toContain("魔化咕咕");
    expect(additionalCalculatorPage).toContain("魔化数量");
    expect(additionalCalculatorPage).toContain("骨弓皮肤");
    expect(additionalCalculatorPage).toContain("魔化巫医");
    expect(additionalCalculatorPage).toContain("附加伤害");
    expect(additionalCalculatorPage).toContain("buildAdditionalCalculatorShare");
    expect(additionalCalculatorPage).toContain("onShareAppMessage");
    expect(additionalCalculatorPage).toContain("onShareTimeline");
    expect(additionalCalculatorPage).toContain("#071112");
    expect(apiClient).toContain("getSkyTowerConfig");
    expect(apiClient).toContain("/api/sky-tower");
  });
});
